name: Auto Deploy ke VPS

on:
  push:
    branches:
      - main # Akan berjalan setiap kali ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Eksekusi perintah di VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Masuk ke folder proyek
            cd /var/www/pabriktahu
            
            # Tarik kode terbaru
            git pull origin main
            
            # Install package baru (jika ada)
            npm install
            
            # Build ulang Nuxt
            npm run build
            
            # Restart PM2
            pm2 restart pabriktahu-landing